In [12]:
import pandas as pd
csv_data = pd.read_csv("timing_data.csv", encoding='euc-kr')
csv_data

        code    score_1    score_2    score_3    score_4    score_5
0      60310  72.588142  84.573151   4.472552  99.108323  73.776904
1      95570  99.441812  94.948318  23.278589  84.592169  61.504558
2       6840  34.963284  37.351224  51.031046  42.335747  96.710866
3      54620  33.377850   3.422216  95.207598  60.180080  83.586858
4     265520  62.196318  37.779478  80.308046  67.787871  65.084210
...      ...        ...        ...        ...        ...        ...
2586     547  78.070317  26.534677  94.311121  18.884347  21.699855
2587     545  38.948885  80.191775  39.122149  20.587318  22.358872
2588    3280  81.621239  38.949560  55.180275  86.643255  98.201031
2589   37440  84.378303  14.929743  74.354984  50.429936  96.493224
2590  238490  63.535006  83.512592  59.426403  32.830909   4.739884

[2591 rows x 6 columns]

In [13]:
csv_data.to_json("timing_data.json", orient = "records")